### ISSUE TITLE
aiy.voicehat doesn't exist anymore

### ISSUE THREAD

**Issue by i621148** [JoBergs/RaspiContent#1]
aiy_music_player.py not working anymore.
Same issue as:
https://github.com/google/aiyprojects-raspbian/issues/572

import aiy.audio is now aiy.voice.audio
import aiy.voicehat is unknown

**Comment by dmitriykovalev** [comment]
Right. there was an API change, `aiy.voicehat` doesn't exist anymore. All functionality is still there, please take a look at the docs, https://aiyprojects.readthedocs.io/en/latest/

**Comment by JoBergs** [comment]
Hello,
thanks for the notice!

I've solved the AIY voice issues, but mpsyt has changed as well.
My current implementation works, but AIY voices an error message.
I'll contact Google and update afterwards.

**Comment by JoBergs** [comment]
Ok so i changed the script and it works now.
However, before playing a song, AIY voices a warning that something went wrong. I'm fairly certain that'S because 'play' overwrites a google voice command, but i found no way to disactivate that and Google's support wasn't that helpful either.

I'm closing this issue now but if someone has an idea regarding that, please let me know!
